### ISSUE TITLE
LRA，SOM版

### ISSUE THREAD

**Issue by kosugitti** [kosugitti/Exametrika#4]
ついにLRA(ch6)に突入でーす。
p.205のkappaですが，分母にランク数(ncls)Rが入ってますよね。
コードの方ではmaxTまで最初にざっとリストをつくっていますが，分母にRが見当たりません。
kaplist = 
  Table[((maxT - t)*kap1 + (t - 1)*kapT)/(maxT - 1), {t, 1, maxT}];

**Comment by kosugitti** [comment]
SOM，やってみました。あー，楽しい。
これは100回回し切るようになってるんですね。試しに200,1000,2000とあげていったら，どんどんloglikが大きくなっていくので「ほおお？」と思ってます。終わりどころがわからない。
一つの基準として，Rank Reference Matrixが1セルあたり平均0.001以上変化しなくなったら止める，というのを考えました。
847回まわりました。

**Comment by sh0j1ma** [comment]
P205の件、おっしゃるとおりです。こちらは、テキストの方が間違いでした。分母がR(T-1)ではなくT-1が正解です。Errataに反映させました。あざっす！

そうなんす。SOMは終わりどころが分からないんですよね。おっしゃるとおり。収束するまで回すと、過学習（過適合）になっちゃうかもなー、なんて気持ちもあって、やりすぎない感じで止めたほうがいいのかなーという。。。BICを基準に回せばいいのかもしんないですね。

また、回しすぎるとユーザーを待たせるので快適じゃなくなるのかなー、とかですね。。。結構、いい加減に作っているのがどんどんバレていってますね笑　とはいえ、小杉さんをエンターテインできているのならば、それだけでやったかいがあったというものです笑

そもそもSOMは機械学習系ってこともあって、alphaやsigmaなどチューニングパラメタが多くて、制御するのが難しいですよね。そんなこんなでSOMのメカニズムからは少しずつ心が離れていって、GTMに行ったのでした笑

**Comment by kosugitti** [comment]
BICの変化でみたら，616回で変化が1e-4以下になりました。これがいいかどうかはともかく。
![Rplot](https://github.com/kosugitti/Exametrika/assets/6091349/4d34555f-dd16-4336-820c-1f1ce2194284)

**Comment by sh0j1ma** [comment]
おおおー、収束はええぇええ！！！！！いいかも！

**Comment by kosugitti** [comment]
これ、学習係数をmaxTにして、それ以降も回るときはその係数を変えないようにするようにしました。単に最大反復数を上げると、最初の学習が遅くてw

**Comment by sh0j1ma** [comment]
なるほど！確かに。上の図はmaxT=100のときですか？t=200のときに変曲点がありますね。おもろ！

**Comment by kosugitti** [comment]
LRA_GTMの最後のソート(P.220)ってコードにふくまれてますか・・・？

**Comment by sh0j1ma** [comment]
げげ、抜けてますね。。。ご指摘あざっす！プログラム更新しておきました。
modフォルダのModule_IRP.nbのemclusモジュールの中、clsrefmat=...の下に
If[mic == 1, clsrefmat = Sort /@ clsrefmat];
を追加しておきました。あざっす！！！！

**Comment by kosugitti** [comment]
すみません，Mathematicaのことはよくわからないんですが，今回手を入れてもらったSort，行・列の方向が逆じゃないでしょうか。mic==1にするとIRPがなんか全然違う形になっちゃって。
Item1のIRP1，mic==0のときに0.585だったのが，mic==1にすると0.07になります。

**Comment by sh0j1ma** [comment]
もう、、、マジですみません。。。おっしゃるとおりです！！すみません！
当該行を転置してソートを掛け、転置で戻すようにしました。
（列ごとにソートをする命令がない（知らない）ので）
If[mic == 1, clsrefmat = Transpose[Sort /@ Transpose[clsrefmat]]];
いつもいつもあざっす！

**Comment by kosugitti** [comment]
よかったでーす！

**Comment by kosugitti** [comment]
おかげさまで，LRA，バッチリ答えが合うところまでできました！ウヒョー，楽しい。
あ，もちろんSOMはダメですw
まあでもSOMのゆるさ，嫌いじゃないんですよねー

**Comment by sh0j1ma** [comment]
おつかれさんです。いろいろと膿み出し、すみません＆あざっす！
SOMの再現性のなさ、やばいっすよね笑　同じデータを分析するときにでも変わってしまうので、
せめて、同じデータを分析するときには同じ結果を返すように、データ由来の性質でもってシードを
決めてあげてます。
SeedRandom[Total[Total[uuu]] + somt];
しかし、ＳＷ間の一致は無理ですね笑

**Comment by kosugitti** [comment]
データの方でシードを決めちゃうのはアイデアですねえ！
Rの方でもデフォルトはこれで，かつ，seedをオプションで入れられるようにします！
