### ISSUE TITLE
Typo in Mathematica

### ISSUE THREAD

**Issue by kosugitti** [kosugitti/Exametrika#8]
しょうもないことですが，表示されるメッセージにタイポが。

「Local **dependenc** ranklustering was selected.」

**Comment by kosugitti** [comment]
Ch11, BINETをやってます。
最後のモデルフィットの出力ですが，Multigroup Model (Table 11.7)もSaturated Model (Table 11.9)も同じ数字が出ています。
mtmk14Ver13でも，Ver12でも確認しました。ご確認いただけますでしょうか。

**Comment by sh0j1ma** [comment]
タイポのコメント、あれれ、全く気付きませんでした。失礼しました！直しておきました。
あと、SWが吐き出すCh11のモデルフィットについても、修正しました。
SWが吐き出す数値が正しいはずなので、テキストの関連部分も合わせて修正して、Errataなどに反映させました。
いよいよ終盤ですね。馬力すげぇ！！！

**Comment by kosugitti** [comment]
いま，最後の詰めをしているところです。
そんな中気づいたのですが，配布されているサンプルデータJ35S515に，学生番号403が二人います！

**Comment by sh0j1ma** [comment]
おお、ほんとや！！！なんでや！！笑
あざっす！修正しました。
