### ISSUE TITLE
LRAの実行後の軸ラベルと横軸メモリの表示について

### ISSUE THREAD

**Issue by phys-ken** [kosugitti/Exametrika#9]
はじめまして。素晴らしいライブラリに感動しています。些細なことですが、要望もかねてissueをはじめて投稿します。
私の解釈ミスでしたらすみません...。

1. LRAを実行した後のIRPの軸ラベルが**Latent Class**になってしまっています。軸ラベルが**Latent Rank** になると、うれしいです。
1.1 RMPの軸ラベルはLatent Rankになっています。TRP,LRDの軸ラベルはLatent Classになってしまっています。 
1. LRAのnclsを少なくしたときのグラフで、横軸メモリに1.5や2.5が表示されないと嬉しいです。

個人的な研究活動で、このライブラリを使用したいと思っています。些細な表記上の問題ですが、修正していただけると嬉しいです。ご確認、よろしくお願いします。

![image](https://github.com/kosugitti/Exametrika/assets/62343651/535676e4-c5a7-4655-bdc5-dfcfeee9b105)

**Comment by kosugitti** [comment]
わー，ありがとうございます。使ってくれて嬉しいです。
ご指摘の点，修正しました！最新バージョンをご確認ください。

**Comment by kosugitti** [comment]
対応できたのでcloseします。もし他にもありましたら別途Issueを立てちゃってください。
